version: "3.8"


services:
  my-app:
    build: ./
    ports:
      - "8080:8080"
    environment:
      DB_IP: my_db
      DB_NAME: eticket_db
      DB_PASSWORD: 8463
    depends_on:
      - my_db
  my_db:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: 8463
      POSTGRES_USERNAME: postgres
      POSTGRES_DB: eticket_db
    volumes:
      - pg_data:/var/lib/postgresql/data
volumes:
  pg_data: