version: "3.8"


services:
  app:
    build: ./
    ports:
      - "8081:8081"
    environment:
      DB_IP: db
      DB_NAME: postgres
      DB_PASSWORD: 8463
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 8463
      POSTGRES_USERNAME: postgres
      POSTGRES_DB: eticket_db
    volumes:
      - pg_data:/var/lib/postgresql/data
volumes:
  pg_data: